packageName: URLR
composerPackageName: urlr/urlr-php
artifactVersion: 2.13.0
invokerPackage: URLR
variableNamingConvention: camelCase
developerOrganization: URLR
developerOrganizationUrl: https://github.com/URLR
artifactUrl: https://github.com/URLR/urlr-php
licenseName: MIT
templateDir: openapi-generator/templates/php-nextgen
